

services:
  backend:
    build: ./backend
    container_name: devinvestor_backend
    ports:
      - "8000:8000"
    restart: always
  frontend:
    build: ./frontend
    container_name: devinvestor_frontend
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
