services:
  backend:
    build: ./backend
    container_name: devinvestor_backend
    ports:
      - "8000:8000"
    restart: always
    volumes: 
      - ./backend:/app
    networks:
      - devinvestor

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devinvestor_frontend
    ports:
      - "80:8501"
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - devinvestor
    env_file:
      - .env

networks:
  devinvestor:
